// For building the open-source release of TalkBack.

apply plugin: 'com.android.application'

apply from: 'shared.gradle'

dependencies {
    implementation project(':talkback')
}

buildscript {
    ext.gradle_plugin_version = "8.13.2"
    ext.kotlin_version = "1.9.25"
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Here we set the version of the Android Gradle Plugin used by this
        // script. It is best to use as new a version as possible, but beware
        // that each version of the Gradle Plugin requires that the version of
        // Gradle (used to drive the build) be a certain version or above. The
        // correspondence is tracked here:
        // https://developer.android.com/build/releases/gradle-plugin#updating-gradle
        classpath "com.android.tools.build:gradle:$gradle_plugin_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

android {
    namespace = "com.android.talkback"
    buildToolsVersion '37.0.0'
    defaultConfig {
        applicationId talkbackApplicationId
        versionName "16.2"
        versionCode 22
        minSdk 26
        targetSdk 36
        compileSdk {
            version = release(36) {
                it.minorApiLevel = 1
            }
        }
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
        multiDexEnabled = true
    }
    packagingOptions {
        exclude 'LICENSE'
        exclude 'README'
    }
    lint {
        checkReleaseBuilds = false
        abortOnError = false
    }
    productFlavors {
        phone {
            dimension "target"
        }
    }
}
