apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply from: "../../shared.gradle"

android {
    namespace = "com.google.android.accessibility.material.flags"
    defaultConfig {
        targetSdk 34
    }
}

dependencies {
    implementation project(':proguard')
}