apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply from: "../../shared.gradle"

android {
    namespace = "com.google.android.accessibility.material.preference"
    defaultConfig {
        targetSdk 34
    }
}

dependencies {
    implementation project(':proguard')
    implementation project(':utils')
    implementation project(':materialpreferencecompose')
}